# Generated by Django 5.2 on 2025-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_civil", models.CharField(max_length=200)),
                ("nome_social", models.CharField(blank=True, max_length=200)),
                ("rg_numero", models.CharField(max_length=50)),
                ("rg_orgao_expedidor", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=14)),
                ("data_nascimento", models.DateField()),
                (
                    "renda_familiar",
                    models.CharField(
                        choices=[
                            ("<1", "menos de um salário mínimo"),
                            ("1", "até um salário mínimo"),
                            ("2-3", "de dois a três salários mínimos"),
                            ("3-4", "de três a quatro salários mínimos"),
                            ("4-5", "de quatro a cinco salários mínimos"),
                            (">5", "mais de cinco salários mínimos"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "territorio",
                    models.CharField(
                        choices=[
                            (
                                "metropolitana",
                                "Território Região Metropolitana de Natal",
                            ),
                            ("agreste", "Território Agreste / Litoral Sul"),
                            ("mato_grande", "Território Mato Grande"),
                            ("potengi", "Território Potengi"),
                            ("trairi", "Território Trairí"),
                            (
                                "sertao_central",
                                "Território Sertão Central Cabugi / Litoral Norte",
                            ),
                            ("serido", "Território Seridó"),
                            ("assu_mossoro", "Território Assú / Mossoró"),
                            ("apodi", "Território Sertão do Apodi"),
                            ("alto_oeste", "Território Alto Oeste"),
                        ],
                        max_length=50,
                    ),
                ),
                ("telefone", models.CharField(max_length=20)),
                (
                    "genero_sexualidade",
                    models.CharField(
                        choices=[
                            ("travesti", "Travesti"),
                            ("mulher_transexual", "Mulher Transexual"),
                            ("homem_transexual", "Homem Transexual"),
                            ("intersexual", "Intersexual"),
                            ("nao_binario", "Não Binárie"),
                            ("trans_masculine", "Trans Masculine"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("negra", "Negra"),
                            ("indigena", "Indígena"),
                            ("cigana", "Cigana"),
                            ("quilombola", "Quilombola"),
                            ("parda", "Parda"),
                            ("branca", "Branca"),
                            ("amarela", "Amarela"),
                        ],
                        max_length=20,
                    ),
                ),
                ("populacao_de_rua", models.BooleanField(default=False)),
                ("rg_anexo", models.FileField(upload_to="documentos/")),
                ("cidade", models.CharField(max_length=20)),
                ("pontuacao", models.FloatField(default=0)),
            ],
        ),
    ]
